#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_design' in
 * file './soc_design.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'pio_input_2_hps', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_INPUT_2_HPS_'.
 * The prefix is the slave descriptor.
 */
#define PIO_INPUT_2_HPS_COMPONENT_TYPE altera_avalon_pio
#define PIO_INPUT_2_HPS_COMPONENT_NAME pio_input_2_hps
#define PIO_INPUT_2_HPS_BASE 0x0
#define PIO_INPUT_2_HPS_SPAN 16
#define PIO_INPUT_2_HPS_END 0xf
#define PIO_INPUT_2_HPS_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_INPUT_2_HPS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_INPUT_2_HPS_CAPTURE 1
#define PIO_INPUT_2_HPS_DATA_WIDTH 32
#define PIO_INPUT_2_HPS_DO_TEST_BENCH_WIRING 0
#define PIO_INPUT_2_HPS_DRIVEN_SIM_VALUE 0
#define PIO_INPUT_2_HPS_EDGE_TYPE RISING
#define PIO_INPUT_2_HPS_FREQ 50000000
#define PIO_INPUT_2_HPS_HAS_IN 1
#define PIO_INPUT_2_HPS_HAS_OUT 0
#define PIO_INPUT_2_HPS_HAS_TRI 0
#define PIO_INPUT_2_HPS_IRQ_TYPE NONE
#define PIO_INPUT_2_HPS_RESET_VALUE 65535

/*
 * Macros for device 'pio_output_2_fpga', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_OUTPUT_2_FPGA_'.
 * The prefix is the slave descriptor.
 */
#define PIO_OUTPUT_2_FPGA_COMPONENT_TYPE altera_avalon_pio
#define PIO_OUTPUT_2_FPGA_COMPONENT_NAME pio_output_2_fpga
#define PIO_OUTPUT_2_FPGA_BASE 0x10
#define PIO_OUTPUT_2_FPGA_SPAN 16
#define PIO_OUTPUT_2_FPGA_END 0x1f
#define PIO_OUTPUT_2_FPGA_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUTPUT_2_FPGA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUTPUT_2_FPGA_CAPTURE 0
#define PIO_OUTPUT_2_FPGA_DATA_WIDTH 32
#define PIO_OUTPUT_2_FPGA_DO_TEST_BENCH_WIRING 0
#define PIO_OUTPUT_2_FPGA_DRIVEN_SIM_VALUE 0
#define PIO_OUTPUT_2_FPGA_EDGE_TYPE NONE
#define PIO_OUTPUT_2_FPGA_FREQ 50000000
#define PIO_OUTPUT_2_FPGA_HAS_IN 0
#define PIO_OUTPUT_2_FPGA_HAS_OUT 1
#define PIO_OUTPUT_2_FPGA_HAS_TRI 0
#define PIO_OUTPUT_2_FPGA_IRQ_TYPE NONE
#define PIO_OUTPUT_2_FPGA_RESET_VALUE 4294967295


#endif /* _ALTERA_HPS_0_H_ */
